/*
	@since: 13/05/2025
	@desc: Tabela responsável por armazenar a hierarquia de usuários do sistema.
*/
CREATE TABLE TIPO_USUARIO(
	TIPO_ID SERIAL PRIMARY KEY,
	TIPO_NOME VARCHAR(50) NOT NULL
);

/*
	@since: 13/05/2025
	@desc: Tabela responsável por armazenar a usuários do sistema.
*/
CREATE TABLE USUARIOS(
	USU_ID SERIAL PRIMARY KEY,
	USU_NOME VARCHAR(32) UNIQUE  NOT NULL, -- Nome do usuário
	USU_SENHA VARCHAR(64) NOT NULL,
	USU_EMAIL VARCHAR(72) NOT NULL,
	USU_CPF VARCHAR(11) UNIQUE NOT NULL,
	USU_TELEFONE VARCHAR(11) NOT NULL,
	USU_ENDERECO VARCHAR(255) NOT NULL,
	USU_DATANASC DATE NOT NULL,
	USU_SEXO VARCHAR(1) CHECK(USU_SEXO IN('M', 'F')) NOT NULL,
	USU_STATUS VARCHAR(1) CHECK (USU_STATUS IN ('S', 'N')),
	TIPO_ID INTEGER REFERENCES TIPO_USUARIO(TIPO_ID)
);

/*
	@since: 13/05/2025
	@desc: Tabela responsável por armazenar a categorias referentes ao chamado.
*/
CREATE TABLE CATEGORIAS_CHAMADO (
    CAT_ID SERIAL PRIMARY KEY,
    CAT_NOME VARCHAR(100) NOT NULL
);

/*
	@since: 13/05/2025
	@desc: Tabela responsável por armazenar as prioridades referentes ao chamado.
*/
CREATE TABLE PRIORIDADES(
	PRI_ID SERIAL PRIMARY KEY,
	PRI_NOME VARCHAR(50) NOT NULL
);


/*
	@since: 13/05/2025
	@desc: Tabela responsável por armazenar os chamados feito pelo usuário.
*/
CREATE TABLE CHAMADOS(
	CHAM_ID SERIAL PRIMARY KEY,
	CHAM_DATA DATE NOT NULL,
	CHAM_DATA_FECHAMENTO DATE,
	CHAM_DETALHE TEXT,
	CHAM_STATUS VARCHAR(10) CHECK(CHAM_STATUS IN('ABERTO', 'FECHADO')) NOT NULL,
	ATENDENTE_ID INTEGER,
	USU_ID INTEGER REFERENCES USUARIOS(USU_ID),
    CAT_ID INTEGER REFERENCES CATEGORIAS_CHAMADO(CAT_ID),
    PRI_ID INTEGER REFERENCES PRIORIDADES(PRI_ID)
);

/*
	@desc: Tabela para armazenar as interações dos usuários com os chamados.
	@history: 13/05/2025, Remoção do campo INT_TEXTO, pois o mesmo não é mais necessário.
*/
CREATE TABLE INTERACOES_CHAMADO (
    INT_ID SERIAL PRIMARY KEY,
    CHAM_ID INTEGER REFERENCES CHAMADOS(CHAM_ID),
    USU_ID INTEGER REFERENCES USUARIOS(USU_ID),
    INT_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USO_IA BOOLEAN DEFAULT FALSE,
	INT_PERGUNTA TEXT,
	INT_FOI_UTIL BOOLEAN DEFAULT FALSE 
);

/*
	Descontinuado
	@desc: Avaliações dos chamados.

	CREATE TABLE AVALIACOES (
    	AVA_ID SERIAL PRIMARY KEY,
    	CHAM_ID INT REFERENCES CHAMADOS(CHAM_ID),
    	USU_ID INT REFERENCES USUARIOS(USU_ID),
    	AVA_NOTA INT CHECK (AVA_NOTA BETWEEN 1 AND 5),
    	AVA_COMENTARIO TEXT,
    	AVA_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);
*/

/*
	@since 03/05/2025
	@desc: Tabela para armazenar as mensagens trocadas entre os usuários e os atendentes.
*/
CREATE TABLE MENSAGENS (
    msg_id SERIAL PRIMARY KEY,
    cham_id INT NOT NULL REFERENCES chamados(cham_id),
    remetente_id INT NOT NULL,
    mensagem TEXT NOT NULL,
    data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);