CREATE TABLE TIPO_USUARIO(
	TIPO_ID SERIAL PRIMARY KEY,
	TIPO_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIOS(
	USU_ID SERIAL PRIMARY KEY,
	USU_NOME VARCHAR(255) NOT NULL,
	USU_SENHA VARCHAR(64) NOT NULL,
	USU_EMAIL VARCHAR(50) NOT NULL,
	USU_CPF VARCHAR(11) NOT NULL,
	USU_TELEFONE VARCHAR(11) NOT NULL,
	USU_ENDERECO VARCHAR(255) NOT NULL,
	USU_DATANASC DATE NOT NULL,
	USU_SEXO VARCHAR(1) CHECK(USU_SEXO IN('M', 'F')) NOT NULL,
	USU_STATUS VARCHAR(1) CHECK (USU_STATUS IN ('S', 'N')),
	TIPO_ID INTEGER REFERENCES TIPO_USUARIO(TIPO_ID)
);

CREATE TABLE CATEGORIAS_CHAMADO (
    CAT_ID SERIAL PRIMARY KEY,
    CAT_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PRIORIDADES(
	PRI_ID SERIAL PRIMARY KEY,
	PRI_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CHAMADOS(
	CHAM_ID SERIAL PRIMARY KEY,
	CHAM_DATA DATE NOT NULL,
	CHAM_DETALHE TEXT,
	CHAM_STATUS VARCHAR(10) CHECK(CHAM_STATUS IN('ABERTO', 'FECHADO')) NOT NULL,
	USU_ID INTEGER REFERENCES USUARIOS(USU_ID),
    CAT_ID INTEGER REFERENCES CATEGORIAS_CHAMADO(CAT_ID),
    PRI_ID INTEGER REFERENCES PRIORIDADES(PRI_ID)
);

CREATE TABLE INTERACOES_CHAMADO (
    INT_ID SERIAL PRIMARY KEY,
    CHAM_ID INTEGER REFERENCES CHAMADOS(CHAM_ID),
    USU_ID INTEGER REFERENCES USUARIOS(USU_ID),
    INT_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INT_TEXTO TEXT NOT NULL
);

CREATE TABLE AVALIACOES (
    AVA_ID SERIAL PRIMARY KEY,
    CHAM_ID INT REFERENCES CHAMADOS(CHAM_ID),
    USU_ID INT REFERENCES USUARIOS(USU_ID),
    AVA_NOTA INT CHECK (AVA_NOTA BETWEEN 1 AND 5),
    AVA_COMENTARIO TEXT,
    AVA_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM USUARIOS;



